### ISSUE TITLE
docker dev error

### ISSUE THREAD

**Issue by abelnexus** [yassir3wad/laravel-vuexy-spa#1]
i exec : docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d

error:
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/c/xampp/htdocs/laravel-vuexy-spa/api/storage/app/public" to rootfs at "/var/www/public/storage": mkdir /var/lib/docker/overlay2/b193f18f58a6f651b440a3584ab8aa43af6dddc5872b43e89d6c3e2d6f5709e3/merged/var/www/public/storage: read-only file system: unknown

**Comment by yassir3wad** [comment]
Hi @abelnexus, I have reproduced the issue and fixed it.
