### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by Hr-Mohammadian** [yassir3wad/laravel-vuexy-spa#2]
Hi , good job on this , very good starter kit . i was looking for something like this for a long time .
there are 2 issues i can see here .
1)vuexy is a paid template and i think if you want this repo get big with no problem and also respecting other developers work its better if you change template to something open source
2)in docker your using spa/api image , i had to change it to build . i think its better if you build everything on the local instead of addressing spa/api image on docker.

i can help on removing vuexy and also upgrading to vue 3.2 and vite and pinia which are much better.

also by module , you mean something like nwidart modules?

**Comment by yassir3wad** [comment]
Hey @Hr-Mohammadian - thanks!

Can you give me an example of an open-source nice template?

What about creating another repo with the new template, and you can contribute there to the Vue part?

Regarding modules, no it’s not nwidart modules, what I meant is just like a feature/resource, we can update that to avoid confusion!

**Comment by Hr-Mohammadian** [comment]
sure , ill create one asap . btw i still get this error while trying to use docker ; 

Error response from daemon: pull access denied for spa/api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

not sure if its trying to reach docker hub repositories or im just missing some local configs...

**Comment by yassir3wad** [comment]
Seems docker trying to lookup the **spa/api** from the docker hub (which does not really exist) and you didn't do `docker login` before.

Anyway, I just removed the image_name from the docker-compose file: https://github.com/yassir3wad/laravel-vuexy-spa/commit/10b84fc7cbc6dbb8102e33403716472eee118f4f

**Comment by Hr-Mohammadian** [comment]
i commented out 
#elif [ "$ROLE" = "worker" ]; then
#    echo "Running Cron....."
#    crontab /etc/cron.d/my-cron && cron
from start.sh in api folder and it seems to be working ... ill open a new issue as soon as i find a way to reproduce problem. thanks

**Comment by yassir3wad** [comment]
if you don't need the worker container to be started just add the following lines under the **worker** service:
```
profiles:
  - donotstart
```
